"""add npm registry entry scripts column

Revision ID: 10a16a4a1bfd
Revises: c77322316098
Create Date: 2020-06-15 20:30:58.091332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "10a16a4a1bfd"
down_revision = "c77322316098"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "npm_registry_entries",
        sa.Column("scripts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("npm_registry_entries", "scripts")
    # ### end Alembic commands ###
