"""add job_names and graph_ids cols to scans

Revision ID: 4363b7a9ada6
Revises: f70827595ff8
Create Date: 2020-09-25 15:39:28.232632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4363b7a9ada6"
down_revision = "f70827595ff8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scans", sa.Column("graph_ids", postgresql.ARRAY(sa.Integer()), nullable=True)
    )
    op.add_column(
        "scans", sa.Column("job_names", postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "job_names")
    op.drop_column("scans", "graph_ids")
    # ### end Alembic commands ###
