"""add scans table

Revision ID: 4a91e0ce58bf
Revises: 379a0ff9957c
Create Date: 2020-07-21 20:57:55.058523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4a91e0ce58bf"
down_revision = "379a0ff9957c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "inserted_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "queued", "started", "failed", "succeeded", name="scan_status_enum"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scans")
    # https://github.com/sqlalchemy/alembic/issues/278
    op.execute(
        """
        DROP TYPE scan_status_enum
        """
    )
    # ### end Alembic commands ###
