"""drop reports task_id and status columns

Revision ID: 5752b9d007c3
Revises: aaab77c5b14d
Create Date: 2020-06-25 22:14:23.458771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5752b9d007c3"
down_revision = "aaab77c5b14d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "status")
    op.drop_column("reports", "task_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column(
            "task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "reports",
        sa.Column("status", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
