"""add report graph_id column

Revision ID: 61c69159cd7d
Revises: 483c5af6f654
Create Date: 2020-07-30 19:07:39.455804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61c69159cd7d"
down_revision = "483c5af6f654"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("graph_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "graph_id")
    # ### end Alembic commands ###
