"""add graph_id to scan

Revision ID: aad005928179
Revises: 63f04096672e
Create Date: 2020-08-26 14:52:51.830818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aad005928179"
down_revision = "63f04096672e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("graph_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "graph_id")
    # ### end Alembic commands ###
