"""add npm registry entry constraints column

Revision ID: c77322316098
Revises: 5c9047774d37
Create Date: 2020-06-15 20:29:29.672378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c77322316098"
down_revision = "5c9047774d37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "npm_registry_entries",
        sa.Column(
            "constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("npm_registry_entries", "constraints")
    # ### end Alembic commands ###
