"""remove unused top_score column from package_reports

Revision ID: f70827595ff8
Revises: b6dbe0461db7
Create Date: 2020-09-02 16:16:15.019819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f70827595ff8"
down_revision = "b6dbe0461db7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "top_score")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column("top_score", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
